version: '3.8'

services:
  arb-bot:
    build: .
    container_name: rust-arb-bot
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
    environment:
      - RPC_URL=$RPC_URL
      - RUST_LOG=info