name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo check

  docker:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t rust-arb-bot . 